### ISSUE TITLE
WHO organisation page lists lots of files named PYF

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Validator-Actual#14]
**Describe the bug**

[WHO organisation page](https://iativalidator.iatistandard.org/organisation/who) contains lots of instances of a file named PYF, which I assume refers to dataset [who-pyf](https://iatiregistry.org/dataset/who-pyf). I _think_ all the links point to the same URL, and all of them show the dataset as “not an XML file”, which I think is wrong.

**To Reproduce**
1. Go to https://iativalidator.iatistandard.org/organisation/who
2. Wait for page to load fully
3. See 342 datasets in total. 167 of them have the file name "PYF"

**Expected behavior**

I expect to see the 176 datasets listed here:
https://iatiregistry.org/publisher/who

**Screenshots**
![Screenshot 2020-11-19 at 14 33 18](https://user-images.githubusercontent.com/464193/99679734-2decd200-2a74-11eb-9a52-b11bcefdd44e.png)

**Comment by siemvaessen** [comment]
This still seems to be an issue @alexlydiate ? cc @PetyaKangalova

**Comment by andylolz** [comment]
This looks partially fixed now… There are fewer duplicates than before, but there are still 343 files listed, of which only 178 are unique. So it seems like there’s still a problem here.

**Comment by PetyaKangalova** [comment]
This issue has now been fixed.

This was an anomaly - WHO had a bunch of files without a last seen date (which is the timestamp we now use to remove old files) from early September of last year, presumably missed during an upgrade or something else. There were also seven other duplicate  files from various publishers in the same state  which have been removed.

**Comment by andylolz** [comment]
Excellent – thanks!
