### ISSUE TITLE
IOM data not updating

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Validator-Actual#15]
**Describe the bug**
IOM data was updated on 2020-11-17. However, it has not been updated in the IATI Validator.

**To Reproduce**
1. Go to the IOM publisher page on the Validator: https://iativalidator.iatistandard.org/organisation/iom
2. See that data was last updated on `2020-11-14`
3. Go to the IATI Registry: https://iatiregistry.org/publisher/iom
4. See that the data was last updated on `2020-11-17`

**Expected behavior**
Validator updated within a reasonable timeframe (e.g. 24 hours)

See also https://github.com/zimmerman-team/iati.cloud/issues/2504

**Comment by nosvalds** [comment]
@markbrough given we've released V2 with a redesigned backend this issue should no longer be an issue. Can we close this?

**Comment by markbrough** [comment]
Yup this appears to be working well now, thanks @nosvalds!
