### ISSUE TITLE
Validator Documentation missing

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Validator-Actual#20]
**Issue**
A user is not able to see any Validator documentation from https://iativalidator.iatistandard.org/ - a user who is not aware actual documentation exists at has no idea it exists. There is extensive documentation available at https://api-doc.dataworkbench.io/ however this is missing from the https://iativalidator.iatistandard.org/ pages. 

**Expected behavior**
I would expect a clear pointer to the documentation either at https://api-doc.dataworkbench.io/ for now or some other way, a 'Documentation' menu item for example with a simple description on dos and a link to https://api-doc.dataworkbench.io/

**Note**
It seems the https://api-doc.dataworkbench.io/ is tied into the https://test-validator.iatistandard.org/ environment but seems not to exist anymore?!

**Comment by nosvalds** [comment]
@siemvaessen I believe this is no longer relevant after the Validator was brought in-house from d4d and now with the release of V2. Can we close this issue?

**Comment by siemvaessen** [comment]
Unable to review as it would seem https://iativalidator.iatistandard.org/ now needs a passphrase to visit?

**Comment by siemvaessen** [comment]
Yes, can be closed. #closing
