### ISSUE TITLE
Files listed more than once / old + new files available?

### ISSUE THREAD

**Issue by sarahshamiso** [IATI/IATI-Validator-Actual#22]
Taking a look at the files for UN-Habitat in the Validator, there are 2 activity files with the same name: Habitat_Projects.xml

Each of these files has different validation results, indicating that perhaps one file is an older one that has now been replaced (i.e. the older one had critical errors whereas the new one doesn't).

I would expect that the only file available in the Validator would be the one that is currently available on the Registry:
https://iatiregistry.org/dataset/unhabitat-activity

**Comment by andylolz** [comment]
I mentioned [the same problem here](https://github.com/IATI/IATI-Validator-Actual/issues/14#issuecomment-778795634), for [WHO data](https://iativalidator.iatistandard.org/organisation/who):

> […] There are fewer duplicates than before, but there are still 343 files listed, of which only 178 are unique. So it seems like there’s still a problem here.

**Comment by andreaszenasidi** [comment]
@sarahshamiso thanks for reporting this issue. The bug reported earlier https://github.com/IATI/IATI-Validator-Actual/issues/14#issuecomment-778795634 was re-introduced by accident, but it's now resolved.
