### ISSUE TITLE
Can’t clone repo

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Validator-Actual#28]
[I raised this here](https://github.com/IATI/IATI-Validator-Actual/pull/26#issuecomment-829976872), but it might be better as an issue.

**Describe the bug**
It’s not possible to clone the repo following [the steps in the README](https://github.com/IATI/IATI-Validator-Actual#using-git). I suspect that’s because the relevant commit of the iati-rulesets submodule hasn’t been pushed to github.

**To Reproduce**
1. Run:
   ```
   git clone --recurse-submodules https://github.com/IATI/IATI-Validator-Actual.git
   ```
2. See the following error:
   ```
   fatal: remote error: upload-pack: not our ref b74754aa00401470f1713fb1deba8a6f3316c270
   fatal: the remote end hung up unexpectedly
   Fetched in submodule path 'lib/iati-rulesets', but it did not contain b74754aa00401470f1713fb1deba8a6f3316c270. Direct fetching of that commit failed.
   ```

**Comment by nosvalds** [comment]
This should be fixed. Let me know if you still have an issue.

**Comment by andylolz** [comment]
Great, yes – that’s done the trick. Thank you!
