### ISSUE TITLE
Validator not in sync with IATI Registry anymore?

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Validator-Actual#35]
**Describe the bug**
Looking at the https://iativalidator.iatistandard.org/organisations it no longer seems to be in sync with the IATI Registry? The Registry holds 1307 publishers, while the Validator hold 1305. 

**To Reproduce**
1. Go to 'https://iativalidator.iatistandard.org/organisations'
2. Look at orgs found'see: "Found 1305 organisations."'
3. Now go to down to 'https://iatiregistry.org/ '
2. Click on 'see: "1307 Organisations have published so far."'

**Expected behavior**
I would expect the Validator to be in sync with the IATI Registry

**Comment by alexlydiate** [comment]
The Validator sync is currently disabled to protect it's state as we alter the integration to get it's data from other sources - see https://github.com/IATI/IATI-Validator-Actual/issues/34 for details. We don't expect it to take too long.

**Comment by andylolz** [comment]
> We don't expect it to take too long.

@alexlydiate Will you notify here when the issue is fixed?

**Comment by andylolz** [comment]
> We don't expect it to take too long.

@alexlydiate Would you mind notifying here when the issue is fixed?

**Comment by siemvaessen** [comment]
@alexlydiate why close an issue if it's actually still an active and open issue. Best to close issues when they are fixed I'd reckon, rather than preemptively closing them.

**Comment by alexlydiate** [comment]
It's not an issue with this component. This component has no responsibility for syncing, that lies in the validator-server component in this present version of the Validator. Issue moved to https://github.com/IATI/IATI-Validator-Server/issues/19 where, after the new sync is in place, we'll investigate if it is an issue beyond that.
