### ISSUE TITLE
File validation report page silently errors for some files

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Validator-Actual#8]
**Describe the bug**
For some files, when you click on the file validation report, the file validation report page silently errors. In the browser console, you can see that the XHR request to get the validation report fails with error 500. However, the user is not notified and the page appears to continue to be loading.

For example:
World Bank Afghanistan: https://iativalidator.iatistandard.org/view/dqf/files/d0bd6c2a9ac2a02fe8ac9570870cb8b4
USAID Somalia: https://iativalidator.iatistandard.org/view/dqf/files/2d81871c60806f24746367cd6b899c82

**To Reproduce**
1. Open the browser console (right click on page -> inspect) and click on the Network tab
2. Go to the [World Bank Afghanistan file validation report](https://iativalidator.iatistandard.org/view/dqf/files/d0bd6c2a9ac2a02fe8ac9570870cb8b4)
3. See that the page continues to appear to be loading (e.g. blue `Loading report...` is displayed)
4. See in the browser console that the XHR request has failed with Error 500 - while trying to access: https://iativalidator.iatistandard.org/api/v1/iati-files/file/json/d0bd6c2a9ac2a02fe8ac9570870cb8b4.json

**Expected behavior**

* Validation results to be displayed
* User to be informed if there was a server error in accessing the results

**Screenshots**
Dataset suggests it is still trying to load:
![image](https://user-images.githubusercontent.com/688113/94134431-453b8480-fe62-11ea-80c6-5381305c5680.png)

However, browser console shows Error 500:
![image](https://user-images.githubusercontent.com/688113/94134052-cf371d80-fe61-11ea-9b76-456d001e63d1.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome v85, Firefox v81

**Comment by nosvalds** [comment]
Hi @markbrough,

Appreciate the detailed issue report. It seems these errors are no longer occurring. 

- The World Bank Afghanistan - WB-AF.xml - https://iativalidator.iatistandard.org/view/dqf/files/469c2be1e93239f440c48ee2e0d6c128

- USAID Somalia - https://iativalidator.iatistandard.org/view/dqf/files/e6becab5ccf5934802ed29001266df3e

I do see the behaviour you describe if I navigate to the links you provided, but I don't see a way that a normal user would come across this as I have to specify the MD5 hash of a file that doesn't exist anymore. Do you remember how you happened on these links before?

Something we can add to the list to handle gracefully for validator V2, but not something I think warrants fixing in the current version unless I'm missing a real workflow where this is still occurring.

Best,
Nik

**Comment by markbrough** [comment]
Yup - I originally clicked on these files from the respective organisation's page.

I just clicked on a bunch of different files for each organisation and indeed they don't appear to have this issue. Though perhaps it would be worthwhile keeping this issue open for now as I assume it could reappear?

**Comment by nosvalds** [comment]
Hi Mark,

Thanks for the additional detail and regression testing. I'd prefer that we close this issue to keep this list to only active issues. If this issue does occur again we can always re-open this issue or link it to a new issue. Closed issues are still accessible. Let me know if you have concerns with that strategy.

-Nik

**Comment by nosvalds** [comment]
Closing as this is no longer a error that we can reproduce.
